using UnityEngine;
using System.Collections;

public class PowerUpCodes : MonoBehaviour {

	public static PowerUpCodes s;


	public PowerUpDealer.NestedIntArray[] lightCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] shadowCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] fireCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] earthCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] poisonCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] netherCodes = new PowerUpDealer.NestedIntArray[2];
	public PowerUpDealer.NestedIntArray[] iceCodes = new PowerUpDealer.NestedIntArray[2];

	// Use this for initialization
	void Awake () {
		s = this;
	}
	
	// Update is called once per frame
	void Update () {
	
	}
		
}
